<div class="b_footer">
  <div class="b_footer_top">
    <div class="row">
      <div class="logo_footer">
        <a href="/"><img src="./asset/img/logo_ft.png" alt=""></a>
      </div>
      <p class="txt_tel">
        <span>フリーダイヤル</span>
        <a href="tel:0120-78-8169">0120-78-8169</a>
      </p>
      <p class="txt_time">受付時間　9:00～18:00 <br class="show_sp">（土・日・祝祭日・年末年始は除く）</p>
      <p class="txt_address">運営会社：株式会社畠山企画　<br class="show_sp">〒662-0002兵庫県西宮市鷲林寺南町26-13 </p>
      <ul class="l_link">
        <li>
          <a href="#">
            <img src="./asset/img/link_01.png" alt="子どもの笑顔を育む広告代理店 株式会社畠山企画">
          </a>
        </li>
        <li>
          <a href="#">
            <img src="./asset/img/link_02.png" alt="子ども習い事SNSクリエイティブ制作専門店 SNSバイキング">
          </a>
        </li>
        <li>
          <a href="#">
            <img src="./asset/img/link_03.png" alt="子ども習い事専門リスティング広告運用 キッズSNS専科">
          </a>
        </li>
      </ul>
    </div>
  </div><!--/.b_footer_top-->
  <div class="b_footer_bottom">
    <p class="copyright">&copy; HATAKEYAMAKIKAKU inc <br class="show_sp">当サイトに掲載の写真・動画などの無断転載・加工などを一切禁止しております</p>
  </div><!--/.b_footer_bottom-->
</div><!--b_footer-->