<div class="b_header">
  <div class="b_header_top">
    <div class="row">
      <h1 class="logo">
        <a href="/">
          <img src="./asset/img/logo.png" alt="チラシバイキング">
        </a>
      </h1>
      <div class="b_store show_pc">
        <span>子ども習い事チラシ制作専門店</span>
        <ul class="b_store_link">
          <li><a href="#">会社案内</a></li>
          <li><a href="#">サイトポリシー</a></li>
          <li><a href="#">よくあるご質問</a></li>
        </ul><!--/.b_store_link-->
      </div><!--/.b_store-->
      <div class="b_contact show_pc">
        <span class="txt_cta">お問い合わせ</span>
        <div class="b_contact_right">
          <div class="right_lf">
            <a href="tel:0120-78-8169">0120-78-8169</a>
            <p>［受付時間］ 9：00～18：00　※土・日・祝祭日・年末年始は除く</p>
          </div>
          <div class="right_rgh">
            <a href="#">メールでのお問い合わせはこちら</a>
          </div>
        </div>
      </div><!--/.b_contact-->
      <div id="icon_nav" class="icon_nav show_sp">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div><!--/.b_header_top-->
  <div class="b_header_bottom">
    <div class="row">
      <nav class="nav" id="nav">
        <ul class="nav_menu">
          <li class="menu_it01">
            <a href="#"><span>トップページ</span></a>
          </li>
          <li class="menu_it02">
            <a href="#"><span>チラシバイキングとは</span></a>
          </li>
          <li class="menu_it03 evChild">
            <a href="#"><span>デザインテンプレート</span></a>
            <div class="box_sub">
              <ul class="nav_menu_sub">
                <li class="sub01">
                  <a href="#">
                    <span class="txt_lg">スイミングスクール</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub02">
                  <a href="#">
                    <span class="txt_lg">学習塾</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub03">
                  <a href="#">
                    <span class="txt_lg">テニススクール</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub04">
                  <a href="#">
                    <span class="txt_lg">キッズダンス</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub05">
                  <a href="#">
                    <span class="txt_lg">体操教室</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub06">
                  <a href="#">
                    <span class="txt_lg">サッカー教室</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub07">
                  <a href="#">
                    <span class="txt_lg">英会話</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub08">
                  <a href="#">
                    <span class="txt_lg">キッズカルチャー</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub09">
                  <a href="#">
                    <span class="txt_lg">プログラミング教室</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub10">
                  <a href="#">
                    <span class="txt_lg">スポーツクラブ</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
                <li class="sub11">
                  <a href="#">
                    <span class="txt_lg">パーソナルジム</span>
                    <span class="txt_sm show_pc">デザインサンプル</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="menu_it04">
            <a href="#"><span>制作料金</span></a>
          </li>
          <li class="menu_it05">
            <a href="#"><span>制作の流れ</span></a>
          </li>
          <li class="menu_it06">
            <a href="#"><span>お問い合わせ</span></a>
          </li>
        </ul>
        <!--/.nav_menu-->
        <ul class="l_piv show_sp">
          <li>
            <a href="#">会社案内</a>
          </li>
          <li>
            <a href="#">サイトポリシー</a>
          </li>
          <li>
            <a href="#">よくあるご質問</a>
          </li>
        </ul>
        <div class="nav_menuCta show_sp">
          <div class="nav_menuCta_right">
            <div class="right_lf">
              <a href="tel:0120-78-8169">0120-78-8169</a>
              <p>［受付時間］ 9:00~18:00 ※土・日・祝祭日・年末年始は除く</p>
            </div>
            <div class="right_rgh">
              <a href="#"><span>メールでのお問い合わせはこちら</span></a>
            </div>
          </div>
        </div><!--/.nav_menuCta-->
      </nav>
      <!--/.nav-->
    </div>
  </div>
</div>